name: Run Pytest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with coverage
        run: |
          pytest --cov=app --cov-report=term --cov-report=xml

# 上傳覆蓋率報告至 Codecov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
        token: ${{ secrets.CODECOV_TOKEN }}
        # (可選) 指定覆蓋率報告的路徑
        # files: ./coverage/clover.xml,./coverage/cobertura-coverage.xml
        # (可選) 指定報告名稱
        # name: codecov-umbrella